apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dashboard

commonLabels:
  app.kubernetes.io/part-of: nexo-dashboard

resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - frontend.yaml
  - ingress.yaml
